### ISSUE TITLE
Feature request: option to select audio device

### ISSUE THREAD

**Issue by derwaldgeist** [fardog/node-osx-audio#11]
Thanks for this great package. Worked as described. But I am dearly missing an way to:

- inspect which audio devices are available on the Mac
- select on of those

We're trying to hook into the audio chain of a digital audio workstation, and setting the mic input device as the default input just to route to this package seems a bit odd and impractical. Is there any chance to extend this?

Of course, it would also be cool if you could select an output device directly. This would free you from using additional tools like Soundflower. But being able to select the input device is nearly a "must-have" in our case.

**Comment by fardog** [comment]
thanks for the request; at the moment, this package has no official maintainer but I'd absolutely welcome a patch which added this functionality.

marking as `help wanted` if anyone has the opportunity to pick this up.

**Comment by derwaldgeist** [comment]
Thanks for your feedback!

Do you happen to know other packages that provide audio input for macOS or Windows? This would be awesome!

**Comment by fardog** [comment]
i'm now aware of any, sorry. i haven't used macOS in about 4 years, and am really behind on what's available.

**Comment by derwaldgeist** [comment]
Thanks anyways for the info. I’m using getUserMedia() now instead, since I am working on an Electron app and thus have access to a full browser.
