### ISSUE TITLE
Wav file is not readable

### ISSUE THREAD

**Issue by logsol** [fardog/node-osx-audio#6]
Hi there, 

I'm running node v0.10.38 and when I execute the little example script you provide, a wave file is being generated but it doesn't appear to be readable by audio players.

Any ideas?

![screen shot 2015-05-21 at 12 05 57](https://cloud.githubusercontent.com/assets/692826/7746355/dc0afcf2-ffb1-11e4-8838-d27691c87e59.png)
![screen shot 2015-05-21 at 12 06 26](https://cloud.githubusercontent.com/assets/692826/7746356/dc0c8e28-ffb1-11e4-8e2a-7005fe2142b9.png)

**Comment by fardog** [comment]
Hi @logsol; technically it's a WAV file, but it won't have any of the headers necessary for many applications to understand how to read it (it's just the raw data, but none of the description). You could either add this programatically, or open the wav file in an application that allows you to define what you are importing, in this case: Signed 16-bit PCM, Stereo, 44100Hz, in little-endian byte-order.

For example, [Audacity](http://web.audacityteam.org/) is a free, open-source application that allows you do do this. Just import the file you've output, and select the above as its format options, then it'll work fine.

If you do end up writing how to add the necessary headers programatically, I would definitely accept a PR updating the example in the README to be more complete.
